---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  data_bags_path: ./data_bags

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: OpenSwan
  run_list: ["recipe[openswan-awsvpn::default]"]
  attributes: { Aws_Vpn : { #data_bag_item : 'ec2test', 
                            Local_Networks : ['10.101.0.0/16']} }
  excludes:
    - ubuntu-12.04
  driver_config:
    network:
    - ["private_network", {ip: "172.16.1.11"}]
    - ["forwarded_port", {guest: 179, host: 179, auto_correct: false}]
    - ["forwarded_port", {guest: 500, host: 500, protocol: udp, auto_correct: false}]